# Generated by Django 6.0.6 on 2026-06-04 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urok', models.CharField(max_length=100, verbose_name='Вид транспорта')),
                ('data_nachala', models.CharField(max_length=10, verbose_name='Дата начала')),
                ('oplata', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('novaya', 'Новая'), ('v-rabote', 'Идет обучение'), ('zavershena', 'Обучение завершено')], default='novaya', max_length=20, verbose_name='Статус')),
                ('otzyv', models.TextField(blank=True, verbose_name='Отзыв')),
                ('sozdana', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-sozdana'],
            },
        ),
    ]
