# Generated by Django 6.0.5 on 2026-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='urok',
            field=models.CharField(max_length=100, verbose_name='Урок'),
        ),
    ]
